### PR TITLE
[WIP] Stop setting dataValue after an Ajax call, it's unnecessary

### PR DESCRIPTION
**Pull request by weaverryan**
Yup, we never needed this. It means we can remove our custom format and always return ~~JSON~~ html.

Why? How? Stimulus is amazing. When we re-render a component, it naturally renders with an updated `data-live-data-value` attribute. Stimulus has mutation observers that *watch* for these changes and update `this.dataValue` in the controller when that happens. So basically, the HTML already contains all the info we need AND Stimulus is already doing the work of using that information.

### CODE REVIEW

**Comment by kbond** [comment]
Do you set our custom vnd header in the JS too?

**Comment by kbond** [comment]
> Yup, we never needed this. It means we can remove our custom format and always return JSON

You meant "always return HTML", right

**Comment by weaverryan** [comment]
Yes, I meant html.

And yes, we would continue to set a custom vnd in the header in js, but it would be a different mime type (one for html) and I think it would only change how a redirect response looks (everything else would always be normal html)

**Comment by kbond** [comment]
I think what you said in slack would be best: 204 response with a location header.

**Pull request closed without merging**
